### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by moan0s** [moan0s/ILMO#38]
There you can set global variables like opening days, e-mail texts or maximum loan time.

**Comment by GerJuli** [comment]
Start with merge 7b38c14 is made

**Comment by GerJuli** [comment]
settings.ini is there

**Comment by moan0s** [comment]
With 2c47e1f5025c030fa394ff70df85e3c06f0b2c65 the status in the header and the opening times information text can be set.

I therfore close this issue and suggest to open a new one for new setting features
