### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by moan0s** [moan0s/ILMO#45]
establishing an installation procedure.

**Comment by GerJuli** [comment]
Automated creation and and modification of database is done. Need to create first user and installation script for library settings

**Comment by GerJuli** [comment]
Important: Insert first user (admin) as one admin is necessary to add more user. Also add issue mail in table lib_log. What about opening hours?

**Comment by bishalkar** [comment]
should i edit the code ?

**Comment by moan0s** [comment]
Added with 9c9294dff1dd690d46f8c5999c8ee9c022ab6d59
