### ISSUE TITLE
White site after installation

### ISSUE THREAD

**Issue by Sebastian1515** [moan0s/ILMO#71]
There is a white site after the installation. Accesing the main page also redirects to .../install/create_user/ .

Fatal error: Uncaught ArgumentCountError: Too few arguments to function User::__construct(), 0 passed in C:\xampp\htdocs\ILMO\install\create_user\index.php on line 23 and exactly 1 expected in C:\xampp\htdocs\ILMO\class\user.php:4 Stack trace: #0 C:\xampp\htdocs\ILMO\install\create_user\index.php(23): User->__construct() #1 {main} thrown in C:\xampp\htdocs\ILMO\class\user.php on line 4

Workaround: rename/ delete the folder install

**Comment by moan0s** [comment]
Should work, if not reopen
