### ISSUE TITLE
Table table_token not defined during installation

### ISSUE THREAD

**Issue by Sebastian1515** [moan0s/ILMO#72]
Warning: Use of undefined constant TABLE_TOKEN - assumed 'TABLE_TOKEN' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\ILMO4\config\db_array.inc.php on line 243

**Comment by moan0s** [comment]
Thanks for the fix! The usual naming scheme is only *token* instead of *table_token*. After a change I can merge the fix.

**Comment by Sebastian1515** [comment]
> 
> 
> Thanks for the fix! The usual naming scheme is only _token_ instead of _table_token_. After a change I can merge the fix.

Fixed in 66c4c43.
