### ISSUE TITLE
Relogin failed

### ISSUE THREAD

**Issue by Sebastian1515** [moan0s/ILMO#75]
Logging out and then in failed. Deleting the password hash in the database solves the problem temporary. Regarding to class/data.php:267 the field 'password' should set to ' ', but this don't work´.
Guess: Problems with the hash storing function.
Hotfix: Comment line 269 ( "$oUser->save_user($aUser);") in class/data.php out.

**Comment by moan0s** [comment]
Oh well, that was quite stupid of me to implement it twice (and wrong once 😂). What I did wrong was to not distinguish between the plaintex password and the coloum *password* in the database, as the coloumn stores the legacy md5-hash...
I checked other calls of this function and f71cf4a should work and not break anything else.
