### ISSUE TITLE
Add User-Id to passwort reset mail

### ISSUE THREAD

**Issue by Sebastian1515** [moan0s/ILMO#76]
For resetting the password the user id is needed but most user don't know there id. Adding the Id to the reset mail helps the users.

**Comment by moan0s** [comment]
I understand 9b4c3cd and 9060fdd but maybe you can explain why 9297fd0 is necessary?

**Comment by Sebastian1515** [comment]
9297fd0 is neccesarry because minimum_token_hour is requested in class token. But it doesn't really fits to this issue.
