### ISSUE TITLE
Saving settings destroys json file

### ISSUE THREAD

**Issue by Sebastian1515** [moan0s/ILMO#82]
Saving the settings sets some settings to null and destroys the format of the json file.

**Comment by moan0s** [comment]
The settings should in the long term be set via web and not by manual editing. Therfore I would not consider the change of formatting as a bug. Most text editors should be able to reformat json to a more human readable file. Maybe there is a solution to keep the format, but I don't know one. I will add a fix that should help at least. Setting settings to null is a bug I will look into.

**Comment by Sebastian1515** [comment]
Does not fix the problem. Causes error:
`Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\ILMO\class\lang.php on line 36
Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\ILMO\class\lang.php on line 36
Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in C:\xampp\htdocs\ILMO\class\lang.php:36 Stack trace: #0 C:\xampp\htdocs\ILMO\class\lang.php(36): array_merge(Array, NULL) #1 C:\xampp\htdocs\ILMO\class\data.php(15): Lang->set_language('german') #2 C:\xampp\htdocs\ILMO\index.php(19): Data->__construct(Object(Lang)) #3 {main} thrown in C:\xampp\htdocs\ILMO\class\lang.php on line 36`

**Comment by moan0s** [comment]
Can you include steps to reproduce the error?

**Comment by Sebastian1515** [comment]
Some fields still set to null.

```
{"default_language":"german",
"lang":{"english":{"OPENING_TIMES_INFO":null}
,
"german":{"OPENING_TIMES_INFO":null}
}
,
"log_mail":null,
"mail_reminder_interval":"0",
"max_loan_time":null,
"minimum_pw_length":null,
"minimum_token_hours":null,
"opening_days":["monday",
"tuesday",
"wednesday",
"thursday",
"friday"],
"path_mail_log":null,
"timezone":null,
"version":"1.3"}
```

**Comment by moan0s** [comment]
Thanks. I will have a look after my vacation.
Probably a bit more complicated, settings is not finished and full of bugs rn 🙈

**Comment by moan0s** [comment]
Fixed the save of settings (kinda) by improving output. Could still use some improvements, but I would not consider it a big anymore. All setting bugs can be collected in #83 
Closing
